on: push

jobs: 
  compare-branch:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      # - name: Branch name
      #   run: |
      #     echo "running on branch ${GITHUB_REF}"
      - id: timeseries
        uses: rez0n/actions-github-release@main
        env:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: "edarha/nats-go"
          type: "latest"


      - name: show release
        env: 
          RELEASE: ${{steps.timeseries.outputs.release}}
          BRANCH:  GITHUB_REF#*/ 
        run: |
          echo "value: \"${RELEASE}\""
          echo "branch: \"${BRANCH}\""
          get_environment() {
            branch=(${GITHUB_REF#*/})
            echo "value of environment: ${branch[@]}"
            branch=${branch#*release1}
            

            echo "value of environment: ${branch[@]}"
          } 


      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
          GITHUB_REPOSITORY: edarha/nats-go
        with:
          tag_name: 'test12'
          name: 'test12'
          draft: false
          prerelease: false
      
